#pragma once

#define CSCHEMATYPE_GETSIZES_INDEX 3
#define CSCHEMASYSTEM_VALIDATECLASSES 35
#define SCHEMASYSTEM_TYPE_SCOPES_OFFSET 0x190
#define SCHEMASYSTEMTYPESCOPE_OFF1 0x47E
#define SCHEMASYSTEMTYPESCOPE_OFF2 0x2808
#define SCHEMASYSTEM_FIND_DECLARED_CLASS_TYPE 2